export const types = {
    CHANGE_TEXT: '[MAIN_PAGE]_CHANGE_TEXT',
    todos:{
        SET_INITIAL_DATA: '[TODOS_PAGE]_SET_INITIAL_DATA',
        SET_DATA: '[TODOS_PAGE]_SET_DATA',
        SET_SEARCH_VALUE: '[TODOS_PAGE]_SET_SEARCH_VALUE',
        SET_LOADING_STATUS: '[TODOS_PAGE]_SET_LOADING_STATUS',
        SET_ERROR: '[TODOS_PAGE]_SET_ERROR',
    },
    products:{
        SET_INITIAL_DATA: '[PRODUCTS_PAGE]_SET_INITIAL_DATA',
        SET_DATA: '[PRODUCTS_PAGE]_SET_DATA',
        SET_SEARCH_VALUE: '[PRODUCTS_PAGE]_SET_SEARCH_VALUE',
        SET_LOADING_STATUS: '[PRODUCTS_PAGE]_SET_LOADING_STATUS',
        SET_ERROR: '[PRODUCTS_PAGE]_SET_ERROR',
    },
    users:{
        SET_INITIAL_DATA: '[USERS_PAGE]_SET_INITIAL_DATA',
        SET_DATA: '[USERS_PAGE]_SET_DATA',
        SET_LOADING_STATUS: '[USERS_PAGE]_SET_LOADING_STATUS',
        SET_ERROR: '[USERS_PAGE]_SET_ERROR',
    },
};